[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
PLATFORM_ARCHITECTURE = { script = ["uname -m"] }

[config]
default_to_workspace = false

[tasks.test]
command = "echo"
args = ["${PLATFORM_ARCHITECTURE}"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.debug]
command = "cargo"
args = ["build", "--bin=fb4rasp", "--target-dir=target-${PLATFORM_ARCHITECTURE}"]
dependencies = ["format"]

[tasks.run-debug-srv]
command = "cargo"
args = ["run", "--bin=fb4rasp", "--target-dir=target-${PLATFORM_ARCHITECTURE}", "--", "--config=files/config.toml"]
dependencies = ["format"]

[tasks.release]
command = "cargo"
args = ["build", "--release", "--bin=fb4rasp", "--target-dir=target-${PLATFORM_ARCHITECTURE}"]
dependencies = ["format"]

[tasks.deploy-stop-service]
command = "sudo"
args = ["systemctl", "stop", "oled-display"]

[tasks.deploy-start-service]
command = "sudo"
args = ["systemctl", "start", "oled-display"]

[tasks.deploy-bin-file]
command = "sudo"
args = ["cp", "-f", "target-${PLATFORM_ARCHITECTURE}/release/fb4rasp", "/usr/local/bin"]

[tasks.deploy]
dependencies = ["release",
                "deploy-stop-service",
                "deploy-bin-file",
                "deploy-start-service"]

[tasks.debug-client]
command = "cargo"
args = ["build", "--bin=fb4rasp-client", "--target-dir=target-${PLATFORM_ARCHITECTURE}"]
dependencies = ["format"]

[tasks.release-client]
command = "cargo"
args = ["build", "--release", "--bin=fb4rasp-client", "--target-dir=target-${PLATFORM_ARCHITECTURE}"]
dependencies = ["format"]

[tasks.deploy-client-stop-service]
command = "systemctl"
args = ["--user", "stop", "fb4rasp-client"]

[tasks.deploy-client-start-service]
command = "systemctl"
args = ["--user", "start", "fb4rasp-client"]

[tasks.reload-user-systemd]
command = "systemctl"
args = ["--user", "daemon-reload"]

[tasks.deploy-client-bin-file]
command = "cp"
args = ["-f", "target-${PLATFORM_ARCHITECTURE}/release/fb4rasp-client", "${CARGO_MAKE_CARGO_HOME}/bin"]
dependencies = ["release-client"]

[tasks.deploy-client-service-file]
command = "cp"
args = ["-f", "files/fb4rasp-client.service", "${HOME}/.config/systemd/user"]

[tasks.deploy-client]
dependencies = ["release-client",
                "deploy-client-stop-service",
                "deploy-client-bin-file",
                "deploy-client-service-file",
                "reload-user-systemd",
                "deploy-client-start-service"]

[tasks.check-emulation]
command = "cargo"
args = ["check", "--bin", "fb4rasp", "--features=emulation"]

[tasks.run-emulation]
command = "cargo"
args = ["run", "--bin", "fb4rasp", "--features=emulation"]
