[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.debug]
command = "cargo"
args = ["build", "--target-dir=target-arm"]
dependencies = ["format"]

[tasks.run-debug-srv]
command = "cargo"
args = ["run", "--bin=fb4rasp", "--target-dir=target-arm"]
dependencies = ["format"]

[tasks.release]
command = "cargo"
args = ["build", "--release", "--target-dir=target-arm"]
dependencies = ["format"]

[tasks.deploy-stop-service]
command = "sudo"
args = ["systemctl", "stop", "oled-display"]

[tasks.deploy-start-service]
command = "sudo"
args = ["systemctl", "start", "oled-display"]

[tasks.deploy-file]
command = "sudo"
args = ["cp", "-f", "target-arm/release/fb4rasp", "/usr/local/bin"]

[tasks.deploy]
dependencies = ["release",
                "deploy-stop-service",
                "deploy-file",
                "deploy-start-service"]
